server:
  port: 3000
  address: 0.0.0.0
#  address: 192.168.1.55

spring:
  application:
    name: apirest

  datasource:
    url: jdbc:mysql://localhost:3306/uber_clone?useSSL=false&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.mysql.MySQLSpatialDialect

socket:
  host: 0.0.0.0
  port: 9092


google:
  api:
    key: AIzaSyCB_U6DeVUjo172-bcCrR1kt8_QcZ3A2-c